name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - main # Change this to your main branch name if it's different

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # No build step is needed for HTML/CSS only projects

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_1_CD7E8 }}
          projectId: test-1-cd7e8
