name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          channelId: live
          projectId: otpt-777eo
          expires: 7d
          entryPoint: .
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
