name: Daily Maintenance

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *' # Runs every day at 3 PM UTC

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install ESLint
      run: npm install -g eslint

    - name: Install Stylelint
      run: npm install -g stylelint

    - name: Install HTMLHint
      run: npm install -g htmlhint

    - name: Run ESLint for JS
      run: eslint '**/*.js' --format stylish

    - name: Run Stylelint for CSS
      run: stylelint '**/*.css' --syntax css

    - name: Run HTMLHint
      run: htmlhint 'public/**/*.html'

    - name: Upload Lint Results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: lint-results
        path: lint-results.xml

  fix:
    runs-on: ubuntu-latest
    needs: lint
    if: always() # Run this job regardless of the outcome of the lint job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install ESLint
      run: npm install -g eslint

    - name: Install Stylelint
      run: npm install -g stylelint

    - name: Install HTMLHint
      run: npm install -g htmlhint

    - name: Auto-fix ESLint issues
      run: eslint 'public/**/*.js' --fix

    - name: Auto-fix Stylelint issues
      run: stylelint 'public/**/*.css' --fix --syntax css

    - name: Auto-fix HTMLHint issues
      run: htmlhint 'public/**/*.html' --fix

    - name: Commit and push fixes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout -b fix/bugfixes
        git add .
        git commit -m "Automated bug fixes"
        git push origin fix/bugfixes

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automated bug fixes"
        branch: fix/bugfixes
        title: "Automated Bug Fixes"
        body: "This PR contains automated bug fixes from the daily maintenance workflow."
